### ISSUE TITLE
The Output file format？

### ISSUE THREAD

**Issue by YuzukiTsuru** [s603122001/Vocal-Melody-Extraction#2]
The Output file format
```
1.000000000000000000e+00 5.851317942364757073e+03
1.000000000000000000e+00 5.826317942364756163e+03
1.000000000000000000e+00 5.826317942364756163e+03
1.000000000000000000e+00 5.776317942364757073e+03
0.000000000000000000e+00 0.000000000000000000e+00
0.000000000000000000e+00 0.000000000000000000e+00
0.000000000000000000e+00 0.000000000000000000e+00
```
what the mean of them
thanks for your reply！

**Comment by rytrose** [comment]
@s603122001 bump! My assumption is `VAD/confidence : freq [Hz]` but is that correct?

**Comment by s603122001** [comment]
@rytrose You are right with the first column which indicates the presence of voice activity, but for the second column, it actually indicates the frequencies in cents.
 (You can find more information [here](https://craffel.github.io/mir_eval/#module-mir_eval.melody))

**Comment by rytrose** [comment]
Ah, perfect, thanks for the info! And the model of course :)

**Comment by annahung31** [comment]
What's the unit of the first column? Is it 20ms?

**Comment by s603122001** [comment]
@annahung31 Yes, you are right. The output time step is 20ms.

**Comment by annahung31** [comment]
Thanks for the reply!
