### ISSUE TITLE
training and testing for symbolic data 

### ISSUE THREAD

**Issue by annahung31** [s603122001/Vocal-Melody-Extraction#3]
Hi, thanks for the model!
In the paper, a MIDI dataset was used as training data, but train.py only deal with audio, as well as the testing process. Does that mean you always transfer the MIDI to audio for the model?
Also, there is no code available for transferring the output text to midi format, If this is something you have, I would really appreciate it if you would post the code to github or share with me. Thank you so much for your help.

**Comment by s603122001** [comment]
@annahung31 
The code for the symbolic model will be uploaded in the next few weeks. Basically it works in the same way as the audio model, the major difference is the input data representation: audio model uses time-frequency representation and the symbolic model uses piano roll. So for your question, we actually transfer the MIDI to piano roll. 

For transferring the output to MIDI, that is beyond the scope of this project, but you can try [this](https://github.com/s603122001/Music-Style-Transfer/blob/master/project/midi_handler.py).

**Comment by annahung31** [comment]
I got it, thank you for your effort!

**Comment by halil-erdogan** [comment]
Hi @s603122001 , thanks for the project. 👏 

Are you planning to upload the code for symbolic model in the future?

Have a nice day. 💯
